#!/bin/bash

## Create backup folder
if ! [ -d ~/config_backup ]; then
	mkdir -pv ~/config_backup
fi

CONFIGS=("terminator" "ranger" "neofetch" "htop" "zathura"
  "autostart" "conky" "polybar" "redshift" "rofi" "vis"
)

for CONFIG in "${CONFIGS[@]}"; do
  if [ -d ~/.config/$CONFIG ] && [ ! -L ~/.config/$CONFIG ]; then
    mv -iv ~/.config/$CONFIG ~/config_backup
  fi
done
if [ -d ~/.moc ] && [ ! -L ~/.moc ]; then
	mv -iv ~/.moc ~/config_backup
fi
