#!/bin/bash

ln -s ~/dotfiles/.config/autostart ~/.config/autostart
ln -s ~/dotfiles/.config/conky ~/.config/conky
ln -s ~/dotfiles/.config/moc ~/.moc
ln -s ~/dotfiles/.config/neofetch ~/.config/neofetch
ln -s ~/dotfiles/.config/polybar ~/.config/polybar
ln -s ~/dotfiles/.config/ranger ~/.config/ranger
ln -s ~/dotfiles/.config/redshift ~/.config/redshift
ln -s ~/dotfiles/.config/rofi ~/.config/rofi
ln -s ~/dotfiles/.config/terminator ~/.config/terminator
ln -s ~/dotfiles/.config/vis ~/.config/vis
