#!/bin/bash

# Create symbolic link for dotfiles
ln -s ~/dotfiles/.aliases ~/.aliases
ln -s ~/dotfiles/.bash_logout ~/.bash_logout
ln -s ~/dotfiles/.bashrc ~/.bashrc
ln -s ~/dotfiles/.gitconfig ~/.gitconfig
ln -s ~/dotfiles/.p10k.zsh ~/.p10k.zsh
ln -s ~/dotfiles/powerlevel10k ~/powerlevel10k
ln -s ~/dotfiles/.profile ~/.profile
ln -s ~/dotfiles/.vimrc ~/.vimrc
ln -s ~/dotfiles/.zsh ~/.zsh
ln -s ~/dotfiles/.zshrc ~/.zshrc

# local bin
sudo ln -s ~/dotfiles/bin/dps /usr/local/bin/dps
sudo ln -s ~/dotfiles/bin/gap /usr/local/bin/gap
sudo ln -s ~/dotfiles/bin/movescreen.py /usr/local/bin/movescreen.py
sudo ln -s ~/dotfiles/bin/ssound /usr/local/bin/ssound
cd /usr/local/bin
sudo chmod +x dps
sudo chmod +x gap
sudo chmod +x movescreen.py
sudo chmod +x ssound

## No longer needed
: <<'END'
if [ -f ~/.imwheelrc ]; then
	mv ~/.imwheelrc ~/dotfiles_backup/.imwheelrc
fi
END
