#!/bin/bash

# Move existing dotfiles to backup folder
if ! [ -d ~/dotfiles_backup ]; then
	mkdir -pv ~/dotfiles_backup
fi

DOTFILES=(".profile" ".aliases" ".gitconfig" ".vimrc"
  ".bash_logout" ".bashrc" ".bash_aliases"
  ".zshrc" ".zsh" ".p10k.zsh" "powerlevel10k"
)

for DOTFILE in "${DOTFILES[@]}"; do
  if ([ -f ~/$DOTFILE ] || [ -d ~/$DOTFILE ]) && [ ! -L ~/$DOTFILE ]; then
    mv -v ~/$DOTFILE ~/dotfiles_backup
  fi
done

echo; echo "Dotfiles are backup at ~${HOME}/dotfiles_backup"
