#!/bin/bash

# Create symbolic links for dotfiles
echo "Creating symbolic links for rc files .."
DOTFILES=(".gitconfig" ".vimrc"
  ".profile" ".aliases" ".bash_logout" ".bashrc"
  ".zshrc" ".zsh" ".p10k.zsh" "powerlevel10k"
)
for DOTFILE in "${DOTFILES[@]}"; do
  if [ -f ~/$DOTFILE ] || [ -d ~/$DOTFILE ]; then
    rm -v ~/$DOTFILE
  fi
  ln -sv ~/dotfiles/dfs/$DOTFILE ~/$DOTFILE
done

# Create symbolic links for local binaries
echo; echo "Creating symbolic links for local binaries .."
BINARIES=("dps" "gap" "movescreen.py" "ssound" "pdfcompress" "pdfcompressDir")
for BINARY in "${BINARIES[@]}"; do
  if [ -f /usr/local/bin/$BINARY ]; then
    sudo rm -v /usr/local/bin/$BINARY
  fi
  sudo ln -sv ~/dotfiles/bin/$BINARY /usr/local/bin/$BINARY
  sudo chmod +x /usr/local/bin/$BINARY
done

echo; echo "Symbolic links for dotfiles are created. Enjoy :)"
