-- Generated by nwg-displays on 2026-07-27 at 11:32:28. Do not edit manually.

hl.monitor({
    output = "desc:BOE 0x0A3B",
    disabled = true
})
hl.monitor({
    output = "desc:Acer Technologies QG270 H3 1316023393V01",
    mode = "1920x1080@60.0",
    position = "1599x0",
    scale = 1.0
})
