-- Configure each plugins
require('plugins.gitsigns')
require('plugins.which-key')
require('plugins.greeter')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.mason')
require('plugins.neodev')
require('plugins.nvim-cmp')
require('plugins.nvterminal')
require('plugins.glow')
require('plugins.symbols-outline')
-- require('plugins.nvim-tree')
require('plugins.lualine')
require('plugins.comment')
require('plugins.indent-blankline')
